#' Calculate the sample contamination status and contamination level
#' @description This function Calculate contamination status and contamination level
#' by contamination-derived variants.
#' @param variant.level.matrix The function inputs a matrix of variant-level contamination 
#' information generated by \code{\link{classification}};
#' @return The function outputs a matrix of sample-level contamination information.
#' @export
#' @examples
#' variant.level.matrix <- data.frame("Sample" = c("SampleA","SampleB"),
#'                                    "Variant_allele_frequency" = c(0.9850, 0.1036),
#'                                    "Predict.contamination.status" = c(0, 0),
#'                                    "Probability.of.contamination.origin" = c(0.1025, 0.3655))
#' calculate_contamination_level(variant.level.matrix = variant.level.matrix )
calculate_contamination_level<-function(variant.level.matrix){
  cont.res<-list()
  vaf=1
  con.mat<-variant.level.matrix
  name<-unique(con.mat[,1])
  for(i in 1:length(name))
  {
    da<-con.mat[which(con.mat[,'Sample']==name[i]
                      & as.numeric(con.mat[,'Variant_allele_frequency'])>=vaf*0.01),,drop=F]
    loc<-which(da[,'Predict.contamination.status']=='1')
    major.hetro.da<-da[which(as.numeric(da[,'Variant_allele_frequency'])<(1-vaf*0.01)
                             & as.numeric(da[,'Variant_allele_frequency'])>0.5
                             & da[,'Predict.contamination.status']==1),,drop=F]
    minor.hetro.da<-da[which(as.numeric(da[,'Variant_allele_frequency'])<=0.5
                             & da[,'Predict.contamination.status']==1),,drop=F]
    hetro.da<-da[which(as.numeric(da[,'Variant_allele_frequency'])<(1-vaf*0.01)
                       & da[,'Predict.contamination.status']==1),,drop=F]

    if(nrow(major.hetro.da)!=0)
    {
      pre.cl.major<-round(1-median(as.numeric(major.hetro.da[,'Variant_allele_frequency'])),4)
    }else{
      pre.cl.major<-0
    }
    if(nrow(minor.hetro.da)!=0)
    {
      pre.cl.minor<-round(median(as.numeric(minor.hetro.da[,'Variant_allele_frequency'])),4)
    }else{
      pre.cl.minor<-0
    }
    if(pre.cl.minor!=0)
    {
      pre.cl<-pre.cl.minor
    }else{
      if(pre.cl.major!=0)
      {
        pre.cl<-pre.cl.major
      }else{
        pre.cl<-0
      }
    }

    mut.number<-nrow(da)
    homo.num<-length(which(as.numeric(da[,'Variant_allele_frequency'])>=1-vaf*0.01))
    hetro.num<-length(which(as.numeric(da[,'Variant_allele_frequency'])<1-vaf*0.01
                            & as.numeric(da[,'Variant_allele_frequency'])>vaf*0.01 ))
    major.con.var.number<-nrow(major.hetro.da)
    minor.con.var.number<-nrow(minor.hetro.da)

    if(major.con.var.number+minor.con.var.number>=2)
    {
      cont.status<-'YES'
    }else{
      cont.status<-'NO'
    }
    NDC.loc<-which(cont.status=='NO')
    pre.cl[NDC.loc]<-0
    cont.res[[i]]<-cbind(name[i],cont.status,pre.cl,
                         mut.number,homo.num,hetro.num,
                         major.con.var.number,
                         minor.con.var.number)
  }
  re<-do.call(rbind,cont.res)
  colnames(re)<-c('Sample','Contamination status','Contamination level',
                  'Total variant number','Homoplasmic variant number','Heteroplasmic variant number',
                  'Contamination-derived variant number(major)',
                  'Contamination-derived variant number(minor)'
  )
  rownames(re)<-{}
  return(re)
}
